# Generated by Django 5.2.3 on 2025-07-21 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Afisha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "card",
                    models.ImageField(upload_to="afisha_cards/", verbose_name="Image"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                ("day", models.DateField(verbose_name="Event date")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View count"),
                ),
            ],
            options={
                "verbose_name": "Afisha",
                "verbose_name_plural": "Afisha list",
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinar Category",
                "verbose_name_plural": "Webinar Categories",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "card",
                    models.ImageField(upload_to="news_cards/", verbose_name="Image"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View count"),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News list",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vebinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Webinar name")),
                (
                    "author_fullname",
                    models.CharField(max_length=255, verbose_name="Author full name"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("day", models.DateField(verbose_name="Day")),
                ("datetime", models.DateTimeField(verbose_name="Time")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinar",
                "verbose_name_plural": "Webinars",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="CommentVebinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                ("grade", models.PositiveSmallIntegerField(verbose_name="Grade")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "vebinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="news.vebinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinar Comment",
                "verbose_name_plural": "Webinar Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVebinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="Purchased"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "vebinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.vebinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Webinar",
                "verbose_name_plural": "User Webinars",
                "ordering": ["-created_at"],
                "unique_together": {("user", "vebinar")},
            },
        ),
    ]
